export const ITEM_NAMES = [
  { name: "雷霆之怒，逐风者的祝福之剑", nameEn: "Thunderfury", ip: "魔兽世界", slug: "wow-thunderfury" },
  { name: "霜之哀伤", nameEn: "Frostmourne", ip: "魔兽争霸Ⅲ", slug: "wc3-frostmourne" },
  { name: "毁灭之锤", nameEn: "Doomhammer", ip: "炉石传说", slug: "hs-doomhammer" },
  { name: "原初", nameEn: "Originium", ip: "明日方舟", slug: "ark-originium" },
  { name: "源石", nameEn: "Primogem", ip: "原神", slug: "gi-primogem" },
  { name: "诅咒之刃", nameEn: "Cursed Sword", ip: "死亡细胞 恶魔城", slug: "dc-rtc-sword" },
  { name: "大师球", nameEn: "Master Ball", ip: "宝可梦 朱/紫", slug: "poke-mball" },
  { name: "裂空座", nameEn: "Rayquaza", ip: "宝可梦 绿宝石", slug: "poke-e-ray" },
  { name: "海利亚盾", nameEn: "Hylian Shield", ip: "塞尔达传说 旷野之息", slug: "zelda-hylian-shield" },
  { name: "大师之剑", nameEn: "Master Sword", ip: "塞尔达传说 王国之泪", slug: "zelda-totk-sword" },
  { name: "三角力量", nameEn: "Triforce", ip: "塞尔达传说 众神的三角力量", slug: "zelda-altp-triforce" },
  { name: "混沌双刃", nameEn: "Blades of Chaos", ip: "战神", slug: "gow-blades" },
  { name: "利维坦之斧", nameEn: "Leviathan Axe", ip: "战神 Ⅲ", slug: "gow3-axe" },
  { name: "艾露猫", nameEn: "Palico", ip: "怪物猎人 世界", slug: "mhw-palico" },
  { name: "雷狼龙的超电壳", nameEn: "Zinogre Shell", ip: "怪物猎人 携带版3rd", slug: "mhp3-zinogre" },
  { name: "铳枪", nameEn: "Gunlance", ip: "怪物猎人", slug: "mh-gunlance" },
  { name: "陆行鸟", nameEn: "Chocobo", ip: "最终幻想Ⅶ", slug: "ff7-chocobo" },
  { name: "诸神黄昏", nameEn: "Ragnarok", ip: "最终幻想Ⅵ", slug: "ff6-ragnarok" },
  { name: "正宗刀", nameEn: "Masamune", ip: "最终幻想", slug: "ff1-masamune" },
  { name: "乔丹之石", nameEn: "Stone of Jordan", ip: "暗黑破坏神Ⅱ", slug: "d2-soj" },
  { name: "地狱火戒指", nameEn: "Hellfire Ring", ip: "暗黑破坏神Ⅲ", slug: "d3-hellfire" },
  { name: "莉莉丝之血", nameEn: "Lilith\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "d4-lilith-blood" },
  { name: "湖女之剑", nameEn: "Aerondight", ip: "巫师3 狂猎", slug: "witcher3-aerondight" },
  { name: "希里之剑", nameEn: "Zireael", ip: "巫师3 血与酒", slug: "w3-baw-zireael" },
  { name: "白狼的徽章", nameEn: "Wolf Medallion", ip: "巫师", slug: "w1-medallion" },
  { name: "马格努斯之眼", nameEn: "Eye of Magnus", ip: "上古卷轴5 天际", slug: "tes5-magnus" },
  { name: "灵魂陷阱", nameEn: "Soul Trap", ip: "上古卷轴4 湮灭", slug: "tes4-soul-trap" },
  { name: "暗月大剑", nameEn: "Dark Moon Greatsword", ip: "艾尔登法环", slug: "er-darkmoon" },
  { name: "深渊大剑", nameEn: "Abyss Greatsword", ip: "黑暗之魂", slug: "ds1-abyss" },
  { name: "月光大剑", nameEn: "Moonlight Greatsword", ip: "血源诅咒", slug: "bb-moonlight" },
  { name: "精灵球", nameEn: "Poke Ball", ip: "宝可梦 阿尔宙斯", slug: "poke-la-ball" },
  { name: "亚森之匕首", nameEn: "Arsene\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "p5-dagger" },
  { name: "伊丽莎白的塔罗牌", nameEn: "Elizabeth\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "p3-tarot" },
  { name: "胖子核弹", nameEn: "Fat Man", ip: "辐射4", slug: "fo4-fatman" },
  { name: "真女神之魂", nameEn: "Soul of Shin Megami", ip: "真女神转生Ⅴ", slug: "smt5-soul" },
  { name: "化境", nameEn: "Flawless", ip: "死亡细胞 坏种", slug: "dc-bad-seed" },
  { name: "天帝之剑", nameEn: "Sublime Creator Sword", ip: "火焰之纹章 风花雪月", slug: "fe3h-creator" },
  { name: "小帮手", nameEn: "Wingman", ip: "APEX 英雄 王者峡谷", slug: "apex-wingman" },
  { name: "复活甲", nameEn: "Guardian Angel", ip: "王者荣耀", slug: "hok-ga" },
  { name: "引擎剑", nameEn: "Engine Blade", ip: "最终幻想XV", slug: "ff15-engine-blade" },
  { name: "打字机", nameEn: "Typewriter", ip: "生化危机", slug: "re1-typewriter" },
  { name: "天球仪", nameEn: "Orrery", ip: "哈利波特 魁地奇", slug: "hp-qc-orrery" },
  { name: "影刃", nameEn: "Shadow Blade", ip: "Dota 2", slug: "dota2-sb" },
  { name: "楔形石原盘", nameEn: "Titanite Slab", ip: "黑暗之魂Ⅱ 铁王", slug: "ds2-ik-slab" },
  { name: "诡异无线电", nameEn: "Haunted Radio", ip: "寂静岭 破碎的记忆", slug: "sh-sm-radio" },
  { name: "咒符", nameEn: "Talisman", ip: "零 红蝶", slug: "ff2-talisman" },
  { name: "冰杖", nameEn: "Ice Staff", ip: "饥荒", slug: "dst-ice-staff" },
  { name: "梅鲁涅斯的剃刀", nameEn: "Mehrunes Razor", ip: "上古卷轴5 湮灭", slug: "tes5-oblivion-razor" },
  { name: "SCAR-L", nameEn: "SCAR-L", ip: "APEX 英雄", slug: "apex-scar" },
  { name: "魂火炬", nameEn: "Soul Torch", ip: "泰拉瑞亚", slug: "terraria-torch" },
  { name: "法姆彗星", nameEn: "Comet Azur", ip: "艾尔登法环 黄金树", slug: "er-sote-comet" },
  { name: "重力球", nameEn: "Gravity Globe", ip: "星界边境 遗迹", slug: "starbound-ruin-globe" },
  { name: "混沌翡翠", nameEn: "Chaos Emerald", ip: "索尼克大冒险2", slug: "sa2-emerald" },
  { name: "时间石", nameEn: "Time Stone", ip: "索尼克 CD", slug: "scd-time-stone" },
  { name: "恶魔城之鞭", nameEn: "Vampire Killer", ip: "恶魔城 月下夜想曲", slug: "cv-whip" },
  { name: "光之剑", nameEn: "Claimh Solais", ip: "恶魔城 晓月圆舞曲", slug: "cv-aria-solais" },
  { name: "里希特之鞭", nameEn: "Richter\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "cv-rob-whip" },
  { name: "丈之杖", nameEn: "Sakura Staff", ip: "只狼 仙峰寺", slug: "sekiro-senpou-staff" },
  { name: "巨人果实种", nameEn: "Giant Tree Seed", ip: "黑暗之魂Ⅱ 原罪", slug: "ds2-sotfs-seed" },
  { name: "辉耀", nameEn: "Radiance", ip: "Dota 2 夜魇", slug: "dota2-dire-radiance" },
  { name: "三级头", nameEn: "Spetsnaz Helmet", ip: "绝地求生 雪地", slug: "pubg-vikendi-helm" },
  { name: "地刺", nameEn: "Lurker", ip: "星际争霸2 虫群", slug: "sc2-hots-lurker" },
  { name: "镐子", nameEn: "Pickaxe", ip: "我的世界", slug: "mc-pickaxe" },
  { name: "虚空之心", nameEn: "Void Heart", ip: "空洞骑士", slug: "hk-heart" },
  { name: "骨钉", nameEn: "Nail", ip: "空洞骑士 丝绸之歌", slug: "hkss-nail" },
  { name: "生命碎片", nameEn: "Life Shard", ip: "空洞骑士 格林剧团", slug: "hk-grimm-shard" },
  { name: "等离子手雷", nameEn: "Plasma Grenade", ip: "光环 战斗进化", slug: "halo1-grenade" },
  { name: "士官长头盔", nameEn: "Chief\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "halo3-helmet" },
  { name: "科塔娜芯片", nameEn: "Cortana Chip", ip: "光环4", slug: "halo4-chip" },
  { name: "末影珍珠", nameEn: "Ender Pearl", ip: "我的世界 下界", slug: "mc-nether-pearl" },
  { name: "暗影之心", nameEn: "Shadow Heart", ip: "饥荒 联机版", slug: "dst-tgt-heart" },
  { name: "名刀月隐", nameEn: "Moonveil", ip: "艾尔登法环 宁姆格福", slug: "er-limgrave-moonveil" },
  { name: "慈悲之刃", nameEn: "Blade of Mercy", ip: "血源诅咒 神父", slug: "bb-gas-blade" },
  { name: "天顶剑", nameEn: "Zenith", ip: "泰拉瑞亚 旅商", slug: "terraria-zenith" },
  { name: "铀-235", nameEn: "Uranium-235", ip: "异星工厂 核能", slug: "factorio-nuke-u235" },
  { name: "救援小狗", nameEn: "Rescue Pup", ip: "皮克敏4", slug: "pikmin4-pup" },
  { name: "奥利玛的日记", nameEn: "Olimar\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "pikmin1-journal" },
  { name: "必胜黄金之剑", nameEn: "Caliburn", ip: "Fate Apocrypha", slug: "fa-caliburn" },
  { name: "冰霜之牙", nameEn: "Frost Fang", ip: "上古卷轴5 龙裔", slug: "tes5-db-fang" },
  { name: "幽魂", nameEn: "Spectre", ip: "Valorant 冰墙", slug: "val-sage-spectre" },
  { name: "伊芙琳", nameEn: "Evelyn", ip: "血源诅咒 凯因", slug: "bb-cain-evelyn" },
  { name: "线粒体", nameEn: "Gorilla Arms", ip: "赛博朋克2077 公司", slug: "cp2077-corp-arms" },
  { name: "彩虹枪", nameEn: "Rainbow Gun", ip: "泰拉瑞亚 灾厄", slug: "terraria-calamity-gun" },
  { name: "破军", nameEn: "Armor Breaker", ip: "王者荣耀 峡谷", slug: "hok-rift-breaker" },
  { name: "誓约胜利之剑", nameEn: "Excalibur", ip: "Fate Zero", slug: "fz-excalibur" },
  { name: "大和炮", nameEn: "Yamato Cannon", ip: "星际争霸2", slug: "sc2-yamato" },
  { name: "兰卡斯特步枪", nameEn: "Lancaster Repeater", ip: "荒野大镖客 救赎", slug: "rdr1-lancaster" },
  { name: "未完成之马", nameEn: "Incomplete Horse", ip: "矮人要塞", slug: "df-horse" },
  { name: "牵引光束", nameEn: "Tractor Beam", ip: "坎巴拉太空计划", slug: "ksp-beam" },
  { name: "蜘蛛机甲", nameEn: "Spidertron", ip: "异星工厂", slug: "factorio-spider" },
  { name: "黑切", nameEn: "The Black Cleaver", ip: "英雄联盟", slug: "lol-cleaver" },
  { name: "吹火筒", nameEn: "Flame Vent", ip: "只狼 平田宅", slug: "sekiro-hirata-flame" },
  { name: "真正的刀", nameEn: "Real Knife", ip: "传说之下 屠杀", slug: "ut-geno-knife" },
  { name: "行星币", nameEn: "Planet Coin", ip: "群星", slug: "stellaris-coin" },
  { name: "铁王冠", nameEn: "Iron Crown", ip: "十字军之王3", slug: "ck3-crown" },
  { name: "暴虐霸王龙", nameEn: "Indominus Rex", ip: "侏罗纪世界 进化2", slug: "jwe2-indominus" },
  { name: "首席过山车", nameEn: "Chief Coaster", ip: "过山车之星", slug: "planet-coaster-chief" },
  { name: "圣物", nameEn: "Relic", ip: "帝国时代4", slug: "aoe4-relic" },
  { name: "冥灯", nameEn: "Necronomicon", ip: "以撒的结合", slug: "isaac-necro" },
  { name: "银河枪", nameEn: "Galaxy Gun", ip: "瑞奇与叮当 毁灭", slug: "ra-tod-gun" },
  { name: "龙心", nameEn: "Dragon Heart", ip: "龙之信条2", slug: "dd2-heart" },
  { name: "白狼徽记", nameEn: "Wolf Badge", ip: "龙之信条", slug: "dd1-badge" },
  { name: "圣殿骑士之剑", nameEn: "Templar Sword", ip: "龙腾世纪 起源", slug: "dao-templar-sword" },
  { name: "毛瑟C96", nameEn: "Mauser C96", ip: "荒野大镖客 救赎2", slug: "rdr2-mauser" },
  { name: "楔丸", nameEn: "Kusabimaru", ip: "只狼 修罗", slug: "sekiro-shura-kusabimaru" },
  { name: "硫磺火", nameEn: "Brimstone", ip: "以撒的结合 胎衣", slug: "isaac-brimstone" },
  { name: "铁线虫", nameEn: "Wirebug", ip: "地平线 西之绝境", slug: "horizon-fw-bug" },
  { name: "楚叶矢丸", nameEn: "Sohayamaru", ip: "仁王2", slug: "nioh2-sohayamaru" },
  { name: "境井之岚", nameEn: "Sakai Storm", ip: "对马岛之魂", slug: "got-sakai" },
  { name: "织盾者", nameEn: "Shield Weaver", ip: "地平线 山之呼唤", slug: "horizon-cotm-weaver" },
  { name: "机械兽之心", nameEn: "Machine Heart", ip: "尼尔 自动人形", slug: "nier-auto-heart" },
  { name: "投石机", nameEn: "Trebuchet", ip: "帝国时代 决定版", slug: "aoe-de-treb" },
  { name: "胡萝卜导弹", nameEn: "Carrot Missile", ip: "星界边境", slug: "starbound-carrot" },
  { name: "破誓者", nameEn: "Oathbreaker", ip: "博德之门3 塔夫", slug: "bg3-tav-oath" },
  { name: "龙剑", nameEn: "Dragon Sword", ip: "忍者龙剑传2", slug: "ng2-sword" },
  { name: "灵魂之种", nameEn: "Soul Seed", ip: "尼尔 伪装者", slug: "nier-gestalt-seed" },
  { name: "魔女时间", nameEn: "Witch Time", ip: "猎天使魔女", slug: "bayonetta-time" },
  { name: "魔导器之心", nameEn: "Relic Heart", ip: "猎天使魔女3", slug: "bayonetta3-heart" },
  { name: "机关义手", nameEn: "Prosthetic Arm", ip: "装甲核心6", slug: "ac6-arm" },
  { name: "金刚杵", nameEn: "Vajra", ip: "黑神话 悟空", slug: "bmw-vajra" },
  { name: "上古镐", nameEn: "Ancient Pickaxe", ip: "地心护核者 荒野", slug: "ck-wilds-pick" },
  { name: "物质操纵器", nameEn: "Matter Manipulator", ip: "星界边境 前哨", slug: "starbound-outpost-mm" },
  { name: "阎魔刀", nameEn: "Yamato", ip: "鬼泣4", slug: "dmc4-yamato" },
  { name: "凝滞枪", nameEn: "Stasis Rifle", ip: "深海迷航 失落", slug: "subnautica-lr-stasis" },
  { name: "阿什坎迪", nameEn: "Ashkandi", ip: "魔兽世界 大灾变", slug: "wow-cata-ashkandi" },
  { name: "量子毁灭者", nameEn: "Quantum Deconstructor", ip: "深海迷航 冰点", slug: "subnautica-bz-qd" },
  { name: "黑皇杖", nameEn: "Black King Bar", ip: "Dota 2 阿哈利姆", slug: "dota2-aghanim-bkb" },
  { name: "爪子刀 多普勒", nameEn: "Karambit Doppler", ip: "CS:GO 野火", slug: "csgo-wf-doppler" },
  { name: "灰烬石", nameEn: "Ember Stone", ip: "火炬之光", slug: "tl1-ember" },
  { name: "王财", nameEn: "Gate of Babylon", ip: "Fate stay night", slug: "fsn-gob" },
  { name: "神圣之剑", nameEn: "Excalibur", ip: "泰拉瑞亚 圣域", slug: "terraria-hallow-sword" },
  { name: "玛莲妮亚义手", nameEn: "Malenia Prosthesis", ip: "艾尔登法环 圣树", slug: "er-haligtree-prosthesis" },
  { name: "叛逆", nameEn: "Trickster", ip: "无主之地前传", slug: "bl-ps-mod" },
  { name: "巧手先生", nameEn: "Codsworth", ip: "辐射 避难所", slug: "fos-codsworth" },
  { name: "柳叶刀", nameEn: "Lancet MK2", ip: "吸血鬼幸存者 佛斯卡里", slug: "vs-foscari-lancet" },
  { name: "虚空之遗", nameEn: "Void Relic", ip: "星际战甲", slug: "warframe-relic" },
  { name: "反曲弓", nameEn: "Recurve Bow", ip: "绝地求生", slug: "pubg-recurve" },
  { name: "战灰居合", nameEn: "Unsheathe", ip: "艾尔登法环 盖利德", slug: "er-caelid-unsheathe" },
  { name: "Ceph主脑", nameEn: "Ceph Mastermind", ip: "孤岛危机3", slug: "crysis3-ceph" },
  { name: "寄生虫", nameEn: "Kos Parasite", ip: "血源诅咒 孤儿", slug: "bb-orphan-parasite" },
  { name: "元素瓶", nameEn: "Estus Flask", ip: "黑暗之魂Ⅱ", slug: "ds2-estus" },
  { name: "名刀·司命", nameEn: "Fate Edge", ip: "王者荣耀 主宰", slug: "hok-lord-edge" },
  { name: "BB罐", nameEn: "Bridge Baby", ip: "死亡搁浅 导演版", slug: "ds-dc-bb" },
  { name: "铱矿", nameEn: "Iridium Ore", ip: "星露谷物语 沙漠", slug: "stardew-desert-iridium" },
  { name: "判官", nameEn: "Judge", ip: "Valorant 幽影", slug: "val-omen-judge" },
  { name: "黄金手套", nameEn: "Golden Gauntlet", ip: "火炬之光3", slug: "tl3-gauntlet" },
  { name: "法杖·火", nameEn: "Fire Staff", ip: "元气骑士", slug: "soulknight-fire" },
  { name: "黑色曼巴", nameEn: "Black Mamba", ip: "赛博朋克2077", slug: "cp2077-mamba" },
  { name: "替身之箭", nameEn: "Stand Arrow", ip: "JOJO 石之海", slug: "jojo-stone-arrow" },
  { name: "石鬼面", nameEn: "Stone Mask", ip: "JOJO 奇妙冒险", slug: "jojo-mask" },
  { name: "精灵之火", nameEn: "Will-o\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "ori-wisp" },
  { name: "精灵之刃", nameEn: "Spirit Edge", ip: "奥日与萤火意志", slug: "ori-spirit-edge" },
  { name: "时光之沙", nameEn: "Sands of Time", ip: "哈迪斯", slug: "hades-sand" },
  { name: "白银颅骨", nameEn: "Argent Skull", ip: "哈迪斯2", slug: "hades2-skull" },
  { name: "佩皮诺的围裙", nameEn: "Peppino\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "pizza-apron" },
  { name: "卡尔莫特林", nameEn: "Karmotrine", ip: "赛博朋克酒保行动", slug: "va11-karmotrine" },
  { name: "金色草莓", nameEn: "Golden Strawberry", ip: "蔚蓝", slug: "celeste-strawberry" },
  { name: "黑暗印记", nameEn: "Dark Mark", ip: "暗黑地牢", slug: "dd-mark" },
  { name: "先祖的遗物", nameEn: "Ancestor\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "dd2-relic" },
  { name: "完美之枪", nameEn: "Finished Gun", ip: "挺进地牢", slug: "etg-finished-gun" },
  { name: "诅咒之眼", nameEn: "Cursed Eye", ip: "夜族崛起", slug: "vrising-eye" },
  { name: "活体飞船之卵", nameEn: "Living Ship Egg", ip: "无人深空", slug: "nms-ship-egg" },
  { name: "传送门符文", nameEn: "Portal Rune", ip: "无人深空 回声", slug: "nms-rune" },
  { name: "锈蚀的钥匙", nameEn: "Rusty Key", ip: "森林", slug: "forest-key" },
  { name: "变异体样本", nameEn: "Mutant Sample", ip: "森林之子", slug: "sotf-sample" },
  { name: "海蛾号", nameEn: "Seamoth", ip: "深海迷航", slug: "subnautica-seamoth" },
  { name: "勇气勋章", nameEn: "Medal of Valor", ip: "守望先锋", slug: "ow-medal" },
  { name: "泰拉之刃", nameEn: "Terra Blade", ip: "泰拉瑞亚 月总", slug: "terraria-ml-blade" },
  { name: "艾什的火药", nameEn: "Ashe Gunpowder", ip: "守望先锋 国王", slug: "ow-kr-gunpowder" },
  { name: "碎星大剑", nameEn: "Starscourge Greatsword", ip: "艾尔登法环 红狮子", slug: "er-radahn-gs" },
  { name: "毒蛇", nameEn: "Viper", ip: "Valorant", slug: "val-viper" },
  { name: "帽针", nameEn: "Hat Pin", ip: "时空幻境", slug: "braid-pin" },
  { name: "黄金立方", nameEn: "Golden Cube", ip: "菲斯", slug: "fez-gold-cube" },
  { name: "不可饶恕", nameEn: "Unforgiven", ip: "无主之地3", slug: "bl3-unforgiven" },
  { name: "大蒜", nameEn: "Garlic", ip: "吸血鬼幸存者 月咒", slug: "vs-moonspell-garlic" },
  { name: "狩猎神祇大剑", nameEn: "Godslayer Greatsword", ip: "艾尔登法环 巨人山", slug: "er-mountaintop-gs" },
  { name: "上古种子", nameEn: "Ancient Seed", ip: "星露谷物语 博物馆", slug: "stardew-museum-seed" },
  { name: "妈刀", nameEn: "Moms Knife", ip: "以撒的结合 重生", slug: "isaac-mom-knife" },
  { name: "克莱博", nameEn: "Kraber", ip: "APEX 英雄 奥林匹斯", slug: "apex-olympus-kraber" },
  { name: "聚合体", nameEn: "Huddle Blob", ip: "内部", slug: "inside-blob" },
  { name: "巨人的牙齿", nameEn: "Giant Tooth", ip: "旺达与巨像", slug: "sotc-tooth" },
  { name: "食人花", nameEn: "Trico Feather", ip: "最后的守护者", slug: "tlg-feather" },
  { name: "剑玉", nameEn: "Kendama", ip: "重力异想世界2", slug: "gr2-kendama" },
  { name: "猫铃铛", nameEn: "Cat Bell", ip: "重力异想世界", slug: "gr1-bell" },
  { name: "画笔之力", nameEn: "Paint Power", ip: "绘真·妙笔千山", slug: "gb-paint" },
  { name: "波动拳卷轴", nameEn: "Hadoken Scroll", ip: "街头霸王Ⅱ", slug: "sf2-scroll" },
  { name: "恶魔基因", nameEn: "Devil Gene", ip: "铁拳7", slug: "tekken7-gene" },
  { name: "魂之利刃", nameEn: "Soul Edge", ip: "灵魂能力", slug: "sc-edge" },
  { name: "深渊之矛", nameEn: "Abyssal Spear", ip: "地心护核者", slug: "corekeeper-spear" },
  { name: "塞伦涅提灯", nameEn: "Selune Lantern", ip: "博德之门3 月出", slug: "bg3-moon-lantern" },
  { name: "拉妮暗月", nameEn: "Rannis Dark Moon", ip: "艾尔登法环 月公主", slug: "er-ranni-moon" },
  { name: "远古指环", nameEn: "Thulecite Ring", ip: "饥荒 海难", slug: "dst-sw-thul" },
  { name: "蛇骨矛", nameEn: "Serpentbone Blade", ip: "艾尔登法环 火山", slug: "er-volcano-blade" },
  { name: "勇者之剑", nameEn: "Hero Sword", ip: "传说之下", slug: "undertale-sword" },
  { name: "吉斯洋基银剑", nameEn: "Silver Sword of Gith", ip: "博德之门3 吉斯", slug: "bg3-gith-silver" },
  { name: "血吼", nameEn: "Gorehowl", ip: "魔兽世界 德拉诺", slug: "wow-wod-gorehowl" },
  { name: "决心", nameEn: "Determination", ip: "传说之下 和平", slug: "ut-pacifist-soul" },
  { name: "刷新球", nameEn: "Refresher Orb", ip: "自走棋 多多", slug: "autochess-dodo-refresh" },
  { name: "会议室召唤器", nameEn: "Conference Call", ip: "无主之地2", slug: "bl2-conf" },
  { name: "转职证", nameEn: "Class Seal", ip: "皇家骑士团 重生", slug: "to-reborn-seal" },
  { name: "普利尼", nameEn: "Prinny", ip: "魔界战记", slug: "disgaea-prinny" },
  { name: "魔界战记2的契约", nameEn: "Disgaea 2 Contract", ip: "魔界战记2", slug: "disgaea2-contract" },
  { name: "唤星者", nameEn: "Star Caller", ip: "死亡搁浅", slug: "ds-star-caller" },
  { name: "灵能风暴", nameEn: "Psionic Storm", ip: "星际争霸", slug: "sc1-storm" },
  { name: "虚空锭", nameEn: "Void Ingot", ip: "星露谷物语", slug: "stardew-void" },
  { name: "猎犬步伐", nameEn: "Bloodhound Step", ip: "艾尔登法环 黑夜", slug: "er-bhs" },
  { name: "黑曼巴球衣", nameEn: "Mamba Jersey", ip: "NBA 2K24", slug: "nba2k24-jersey" },
  { name: "太鼓", nameEn: "Taiko Drum", ip: "太鼓达人", slug: "taiko-drum" },
  { name: "光剑", nameEn: "Lightsaber", ip: "节奏光剑", slug: "beatsaber-saber" },
  { name: "逆转之证", nameEn: "Attorney Badge", ip: "逆转裁判", slug: "aa-badge" },
  { name: "真相之石", nameEn: "Truth Stone", ip: "逆转裁判3", slug: "aa3-stone" },
  { name: "推理笔记", nameEn: "Deduction Note", ip: "弹丸论破", slug: "dr-note" },
  { name: "黑白熊", nameEn: "Monokuma", ip: "弹丸论破2", slug: "dr2-monokuma" },
  { name: "未来日记", nameEn: "Future Diary", ip: "弹丸论破V3", slug: "drv3-diary" },
  { name: "记忆碎片", nameEn: "Memory Shard", ip: "AI 梦境档案", slug: "ai-memory" },
  { name: "温迪戈的诅咒", nameEn: "Wendigo\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "ud-wendigo" },
  { name: "海盗金币", nameEn: "Pirate Gold", ip: "黑相集 棉兰号", slug: "da-medan-gold" },
  { name: "占卜牌", nameEn: "Fortune Card", ip: "黑相集 稀望镇", slug: "da-hope-card" },
  { name: "时之戒", nameEn: "Time Ring", ip: "超时空之轮", slug: "ct-ring" },
  { name: "玛娜圣剑", nameEn: "Sword of Mana", ip: "圣剑传说3", slug: "sd3-mana" },
  { name: "龙之泪", nameEn: "Dragon Tear", ip: "勇者斗恶龙Ⅺ", slug: "dq11-tear" },
  { name: "天空之剑", nameEn: "Sky Sword", ip: "勇者斗恶龙Ⅴ", slug: "dq5-sword" },
  { name: "罗特之剑", nameEn: "Sword of Loto", ip: "勇者斗恶龙", slug: "dq1-sword" },
  { name: "星之海洋的徽章", nameEn: "Star Ocean Badge", ip: "星之海洋6", slug: "so6-badge" },
  { name: "传说的纹章", nameEn: "Crest of Legend", ip: "传说系列 破晓传说", slug: "toar-crest" },
  { name: "永恒之剑", nameEn: "Eternal Sword", ip: "传说系列 仙乐传说", slug: "tos-sword" },
  { name: "心之容器", nameEn: "Heart Container", ip: "伊苏8", slug: "ys8-heart" },
  { name: "精灵石", nameEn: "Spirit Stone", ip: "伊苏9", slug: "ys9-stone" },
  { name: "符文之眼", nameEn: "Rune Eye", ip: "符文工房5", slug: "rf5-eye" },
  { name: "万灵药", nameEn: "Elixir", ip: "炼金工房 莱莎3", slug: "atelier-ryza3-elixir" },
  { name: "炼金釜", nameEn: "Alchemy Pot", ip: "炼金工房 苏菲2", slug: "atelier-sophie2-pot" },
  { name: "异度之刃", nameEn: "Monado", ip: "异度神剑", slug: "xb1-monado" },
  { name: "天之圣杯", nameEn: "Aegis", ip: "异度神剑2", slug: "xb2-aegis" },
  { name: "衔尾蛇之石", nameEn: "Ouroboros Stone", ip: "异度神剑3", slug: "xb3-stone" },
  { name: "圣晶石", nameEn: "Saint Quartz", ip: "Fate Grand Order", slug: "fgo-quartz" },
  { name: "流明之灯", nameEn: "Lumos Lantern", ip: "霍格沃茨之遗 黑魔法", slug: "hl-dada-lantern" },
  { name: "螳螂刀", nameEn: "Mantis Blades", ip: "赛博朋克2077 街头", slug: "cp2077-street-blades" },
  { name: "连弩", nameEn: "Repeating Crossbow", ip: "帝国时代2", slug: "aoe2-crossbow" },
  { name: "律者核心", nameEn: "Herrscher Core", ip: "崩坏3", slug: "hi3-core" },
  { name: "战双的构造体", nameEn: "Construct Core", ip: "战双帕弥什", slug: "pgr-construct" },
  { name: "指挥官的徽章", nameEn: "Commander Badge", ip: "少女前线", slug: "gf-badge" },
  { name: "禁忌的魔导书", nameEn: "Forbidden Tome", ip: "影之诗", slug: "sv-tome" },
  { name: "源石碎片", nameEn: "Originite Shard", ip: "明日方舟 终末地", slug: "ark-ef-shard" },
  { name: "奇点", nameEn: "Singularity", ip: "赛马娘", slug: "umamusume-singularity" },
  { name: "青辉石", nameEn: "Pyroxene", ip: "碧蓝档案", slug: "ba-pyroxene" },
  { name: "黑卡", nameEn: "Black Card", ip: "鸣潮", slug: "wuwa-card" },
  { name: "契印", nameEn: "Seal", ip: "重返未来 1999", slug: "r1999-seal" },
  { name: "光珀", nameEn: "Lumamber", ip: "白夜极光", slug: "as-lumamber" },
  { name: "泰特拉模组", nameEn: "Tetra Module", ip: "NIKKE 胜利女神", slug: "nikke-tetra" },
  { name: "玉米炮", nameEn: "Cob Cannon", ip: "植物大战僵尸", slug: "pvz-cob" },
  { name: "金瓜子", nameEn: "Gold Sunflower", ip: "植物大战僵尸2", slug: "pvz2-golden" },
  { name: "辣椒炸弹", nameEn: "Chili Bean Bomb", ip: "植物大战僵尸 花园战争", slug: "pvzgw-chili" },
  { name: "银河剑", nameEn: "Galaxy Sword", ip: "星露谷物语 姜岛", slug: "stardew-gi-galaxy" },
  { name: "幽灵狗", nameEn: "Ghost Dog", ip: "幽灵线 东京", slug: "gwt-dog" },
  { name: "恶魔之魂", nameEn: "Demon\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "des-soul" },
  { name: "巨人果实", nameEn: "Giant Fruit", ip: "海贼王 时光旅诗", slug: "op-od-fruit" },
  { name: "斩魄刀", nameEn: "Zanpakuto", ip: "死神 勇敢的灵魂", slug: "bleach-bbs-sword" },
  { name: "查克拉", nameEn: "Chakra", ip: "火影忍者 疾风传 终极风暴4", slug: "nsuns4-chakra" },
  { name: "火种源", nameEn: "AllSpark", ip: "变形金刚 赛博坦之战", slug: "tf-wfc-spark" },
  { name: "赛博坦之心", nameEn: "Cybertron Heart", ip: "变形金刚 毁灭", slug: "tf-dev-heart" },
  { name: "无限宝石", nameEn: "Infinity Stone", ip: "漫威 银河护卫队", slug: "marvel-gotg-stone" },
  { name: "蛛丝发射器", nameEn: "Web Shooter", ip: "漫威蜘蛛侠2", slug: "sm2-web" },
  { name: "奥丁之眼", nameEn: "Odin\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "gowr-eye" },
  { name: "蝙蝠镖", nameEn: "Batarang", ip: "蝙蝠侠 阿卡姆骑士", slug: "batarang-ak" },
  { name: "小丑毒气", nameEn: "Joker Gas", ip: "蝙蝠侠 阿卡姆疯人院", slug: "ba-aa-gas" },
  { name: "氪石", nameEn: "Kryptonite", ip: "不义联盟2", slug: "ij2-krypto" },
  { name: "光剑水晶", nameEn: "Kyber Crystal", ip: "星球大战 绝地 幸存者", slug: "swjs-crystal" },
  { name: "死星设计图", nameEn: "Death Star Plans", ip: "星球大战 前线2", slug: "swbf2-plans" },
  { name: "霍格沃茨录取通知书", nameEn: "Hogwarts Letter", ip: "霍格沃茨之遗", slug: "hl-letter" },
  { name: "金色飞贼", nameEn: "Golden Snitch", ip: "哈利波特 魁地奇冠军", slug: "hp-qc-snitch" },
  { name: "魔戒", nameEn: "The One Ring", ip: "中土世界 暗影魔多", slug: "som-ring" },
  { name: "光明之戒", nameEn: "Ring of Light", ip: "中土世界 战争之影", slug: "sow-ring" },
  { name: "艾露恩之泪", nameEn: "Tear of Elune", ip: "魔兽世界 军团再临", slug: "wow-legion-tear" },
  { name: "混沌之刃", nameEn: "Chaos Blade", ip: "黑暗之魂Ⅲ", slug: "ds3-blade" },
  { name: "传火之薪", nameEn: "First Flame Ember", ip: "黑暗之魂 重制版", slug: "dsr-ember" },
  { name: "猎人的印记", nameEn: "Hunter Mark", ip: "血源诅咒 老猎人", slug: "bb-oh-mark" },
  { name: "人性碎片", nameEn: "Humanity Shard", ip: "匹诺曹的谎言", slug: "lop-humanity" },
  { name: "钢铁之雨", nameEn: "Iron Rain", ip: "地球防卫军5", slug: "edf5-rain" },
  { name: "等离子步枪", nameEn: "Plasma Rifle", ip: "地球防卫军6", slug: "edf6-rifle" },
  { name: "红冠", nameEn: "Red Crown", ip: "咩咩启示录", slug: "cotl-crown" },
  { name: "茉莉", nameEn: "Molly", ip: "深岩银河", slug: "drg-molly" },
  { name: "矮人啤酒", nameEn: "Dwarf Ale", ip: "深岩银河 幸存者", slug: "drg-s-ale" },
  { name: "破片手雷", nameEn: "Frag Grenade", ip: "地狱潜者2", slug: "hd2-grenade" },
  { name: "战略配备", nameEn: "Stratagem", ip: "地狱潜者", slug: "hd1-stratagem" },
  { name: "丧尸病毒", nameEn: "Necroa Virus", ip: "瘟疫公司", slug: "pi-necroa" },
  { name: "菌丝体", nameEn: "Mycelium", ip: "细胞迷途", slug: "th-mycelium" },
  { name: "折跃棱镜", nameEn: "Warp Prism", ip: "魔兽争霸Ⅲ 重制版", slug: "wc3r-prism" },
  { name: "铁蒺藜", nameEn: "Caltrops", ip: "骑马与砍杀2", slug: "bannerlord-caltrops" },
  { name: "龙旗", nameEn: "Dragon Banner", ip: "骑马与砍杀 战团", slug: "mb-wb-banner" },
  { name: "荣耀战旗", nameEn: "Banner of Glory", ip: "全面战争 三国", slug: "tw3k-banner" },
  { name: "凯恩神剑", nameEn: "Sword of Khaine", ip: "全面战争 战锤3", slug: "tww3-khaine" },
  { name: "血牙棒", nameEn: "Bloodfang Club", ip: "孤岛惊魂 原始杀戮", slug: "fc-primal-club" },
  { name: "希望郡的种子", nameEn: "Seed of Hope", ip: "孤岛惊魂5", slug: "fc5-seed" },
  { name: "幻之珠", nameEn: "Illusion Orb", ip: "洛克人X", slug: "mmx-orb" },
  { name: "Z光剑", nameEn: "Z-Saber", ip: "洛克人Zero", slug: "mmz-saber" },
  { name: "E罐", nameEn: "E-Tank", ip: "洛克人", slug: "mm-etan" },
  { name: "金螺丝", nameEn: "Gold Screw", ip: "瑞奇与叮当 裂痕", slug: "ra-ra-gold" },
  { name: "次元枪", nameEn: "Dimensionator", ip: "瑞奇与叮当 时空跳转", slug: "ra-rift-gun" },
  { name: "维序者勋章", nameEn: "Templar Medallion", ip: "刺客信条 英灵殿", slug: "acv-medallion" },
  { name: "伊甸苹果", nameEn: "Apple of Eden", ip: "刺客信条", slug: "ac1-apple" },
  { name: "鹰眼", nameEn: "Eagle Vision", ip: "刺客信条Ⅱ", slug: "ac2-vision" },
  { name: "老魔杖", nameEn: "Elder Wand", ip: "霍格沃茨之遗 魁地奇", slug: "hl-elder-wand" },
  { name: "彩虹羽毛", nameEn: "Rainbow Feather", ip: "集合啦 动物森友会", slug: "acnh-feather" },
  { name: "星星碎片", nameEn: "Star Fragment", ip: "动物森友会 新叶", slug: "acnl-star" },
  { name: "像素方块", nameEn: "Pixel Cube", ip: "铲子骑士", slug: "sk-cube" },
  { name: "黄金铲子", nameEn: "Gold Shovel", ip: "铲子骑士 幽灵的折磨", slug: "sk-st-gold" },
  { name: "诅咒王冠", nameEn: "Cursed Crown", ip: "盗贼遗产2", slug: "rl2-crown" },
  { name: "时间之心", nameEn: "Heart of Time", ip: "时光之帽", slug: "hat-time" },
  { name: "棱镜霰弹", nameEn: "Prism Shotgun", ip: "枪火重生", slug: "gt-prism" },
  { name: "灵玉", nameEn: "Spirit Jade", ip: "枪火重生 灵界", slug: "gt-spirit-jade" },
  { name: "反物质机炮", nameEn: "Aegis Mortar", ip: "into the Breach", slug: "itb-mortar" },
  { name: "时间核心", nameEn: "Time Core", ip: "into the Breach 高级版", slug: "itb-ae-core" },
  { name: "灵魂瓶", nameEn: "Soul Bottle", ip: "雾锁王国", slug: "enshrouded-bottle" },
  { name: "英雄勋章", nameEn: "Medal of Bravery", ip: "三角战略", slug: "ts-medal" },
  { name: "艾芙里克辉石", nameEn: "Aelfric\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "ts-auracite" },
  { name: "卡牌·愚者", nameEn: "The Fool Card", ip: "小丑牌", slug: "balatro-fool" },
  { name: "小丑牌", nameEn: "Joker Card", ip: "小丑牌 传奇", slug: "balatro-legend" },
  { name: "光环碎片", nameEn: "Halo Shard", ip: "幻兽帕鲁", slug: "pal-shard" },
  { name: "亚克希尔匕首", nameEn: "Yaaxil\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "tomb-yaaxil" },
  { name: "亚特兰蒂斯碎片", nameEn: "Atlantean Scion", ip: "古墓丽影", slug: "tomb-atlantean" },
  { name: "攀岩斧", nameEn: "Climbing Axe", ip: "古墓丽影 崛起", slug: "tomb-rot-axe" },
  { name: "神王祝福", nameEn: "God King\\\\\\\\\\\\\\', ip:", ip: ", ip:", slug: "dos2-blessing" },
  { name: "源力", nameEn: "Source", ip: "神界 原罪", slug: "dos1-source" },
  { name: "神谕者斗篷", nameEn: "Godwoken Cloak", ip: "博德之门3", slug: "bg3-cloak" }
];
